from .vgg import *
from .dpn import *
from .lenet import *
from .senet import *
from .pnasnet import *
from .densenet import *
from .googlenet import *
from .shufflenet import *
from .shufflenetv2 import *
from .resnet import *
from .resnext import *
from .preact_resnet import *
from .mobilenet import *
from .mobilenetv2 import *
from .efficientnet import *
from .regnet import *
from .permuted_resnet import *
from .shuffled_filters_resnet import *
from .permuted_resnet_no_constraints import *
from .shuffled_filters_resnet_normalization_play import *
from .resnet_1x1 import *
from .permuted_resnet_dropout_onexone import *
from .squeezenet_cifar import *
from .densenet_depthwise_separable import *
from .resnet_multiple_1x1 import *
from .resnet_multiple_1x1_grouped import *
from .small_CNN import *
from .permconv import *